<?php

if (! defined('ABSPATH')) {
    exit;
}

class EstateOfficeCRM_DB_Schema
{
    /**
     * @return string[]
     */
    public static function get_sql(string $prefix, string $charset_collate): array
    {
        $tables = self::tables($prefix);

        return [
            "CREATE TABLE {$tables['clients']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                client_type VARCHAR(20) NOT NULL,
                first_name VARCHAR(120) NULL,
                last_name VARCHAR(140) NULL,
                company_name VARCHAR(180) NULL,
                representative_name VARCHAR(180) NULL,
                phone VARCHAR(50) NULL,
                email VARCHAR(190) NULL,
                website VARCHAR(190) NULL,
                pesel VARCHAR(20) NULL,
                document_type VARCHAR(40) NULL,
                document_number VARCHAR(80) NULL,
                nip VARCHAR(20) NULL,
                krs VARCHAR(30) NULL,
                regon VARCHAR(30) NULL,
                owner_user_id BIGINT UNSIGNED NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY  (id),
                KEY idx_client_type (client_type),
                KEY idx_phone (phone),
                KEY idx_email (email),
                KEY idx_owner_user_id (owner_user_id)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['client_addresses']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                client_id BIGINT UNSIGNED NOT NULL,
                address_type VARCHAR(30) NOT NULL,
                street VARCHAR(180) NULL,
                building_no VARCHAR(30) NULL,
                apartment_no VARCHAR(30) NULL,
                postal_code VARCHAR(20) NULL,
                city VARCHAR(120) NULL,
                district VARCHAR(120) NULL,
                county VARCHAR(120) NULL,
                precinct VARCHAR(120) NULL,
                plot_number VARCHAR(80) NULL,
                country VARCHAR(120) NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                KEY idx_client_id (client_id),
                KEY idx_address_type (address_type),
                KEY idx_city (city)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['agreements']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                agreement_number VARCHAR(80) NOT NULL,
                transaction_type VARCHAR(20) NOT NULL,
                date_signed DATE NOT NULL,
                date_end DATE NULL,
                is_indefinite TINYINT(1) NOT NULL DEFAULT 0,
                is_exclusive TINYINT(1) NOT NULL DEFAULT 0,
                commission_amount DECIMAL(14,2) NULL,
                commission_unit VARCHAR(10) NULL,
                commission_split_enabled TINYINT(1) NOT NULL DEFAULT 0,
                commission_stages_json LONGTEXT NULL,
                current_stage VARCHAR(100) NOT NULL DEFAULT 'Umowa Posrednictwa',
                owner_user_id BIGINT UNSIGNED NULL,
                created_by BIGINT UNSIGNED NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_agreement_number (agreement_number),
                KEY idx_transaction_type (transaction_type),
                KEY idx_owner_user_id (owner_user_id),
                KEY idx_date_signed (date_signed)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['agreement_clients']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                agreement_id BIGINT UNSIGNED NOT NULL,
                client_id BIGINT UNSIGNED NOT NULL,
                relation_role VARCHAR(40) NULL,
                created_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_agreement_client (agreement_id, client_id),
                KEY idx_client_id (client_id)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['properties']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                agreement_id BIGINT UNSIGNED NULL,
                offer_number VARCHAR(80) NOT NULL,
                transaction_type VARCHAR(20) NOT NULL,
                property_type VARCHAR(30) NOT NULL,
                house_type VARCHAR(40) NULL,
                street VARCHAR(180) NULL,
                building_no VARCHAR(30) NULL,
                apartment_no VARCHAR(30) NULL,
                postal_code VARCHAR(20) NULL,
                city VARCHAR(120) NULL,
                district VARCHAR(120) NULL,
                county VARCHAR(120) NULL,
                gmina VARCHAR(120) NULL,
                precinct VARCHAR(120) NULL,
                plot_number VARCHAR(80) NULL,
                land_registry_no VARCHAR(120) NULL,
                no_land_registry TINYINT(1) NOT NULL DEFAULT 0,
                legal_status VARCHAR(120) NULL,
                latitude DECIMAL(10,7) NULL,
                longitude DECIMAL(10,7) NULL,
                price DECIMAL(14,2) NULL,
                price_currency VARCHAR(3) NOT NULL DEFAULT 'PLN',
                admin_rent DECIMAL(14,2) NULL,
                area DECIMAL(10,2) NULL,
                plot_area DECIMAL(10,2) NULL,
                price_per_m2 DECIMAL(14,2) NULL,
                year_built SMALLINT UNSIGNED NULL,
                floor_no SMALLINT NULL,
                floors_total SMALLINT NULL,
                rooms SMALLINT UNSIGNED NULL,
                bedrooms SMALLINT UNSIGNED NULL,
                bathrooms SMALLINT UNSIGNED NULL,
                toilets SMALLINT UNSIGNED NULL,
                plot_shape VARCHAR(20) NULL,
                plot_length DECIMAL(10,2) NULL,
                plot_width DECIMAL(10,2) NULL,
                plot_dimensions_text VARCHAR(255) NULL,
                description LONGTEXT NULL,
                building_finish VARCHAR(80) NULL,
                exposure_json LONGTEXT NULL,
                view_json LONGTEXT NULL,
                layout_json LONGTEXT NULL,
                kitchen_type VARCHAR(40) NULL,
                parking_json LONGTEXT NULL,
                media_json LONGTEXT NULL,
                amenities_json LONGTEXT NULL,
                equipment_json LONGTEXT NULL,
                extra_areas_json LONGTEXT NULL,
                custom_fields_json LONGTEXT NULL,
                tags_json LONGTEXT NULL,
                is_new_offer TINYINT(1) NOT NULL DEFAULT 0,
                is_exclusive TINYINT(1) NOT NULL DEFAULT 0,
                is_sold TINYINT(1) NOT NULL DEFAULT 0,
                is_rented TINYINT(1) NOT NULL DEFAULT 0,
                is_new_price TINYINT(1) NOT NULL DEFAULT 0,
                no_commission TINYINT(1) NOT NULL DEFAULT 0,
                is_mls_offer TINYINT(1) NOT NULL DEFAULT 0,
                is_premium TINYINT(1) NOT NULL DEFAULT 0,
                export_www TINYINT(1) NOT NULL DEFAULT 0,
                export_portals TINYINT(1) NOT NULL DEFAULT 0,
                new_offer_expires_at DATETIME NULL,
                owner_user_id BIGINT UNSIGNED NULL,
                created_by BIGINT UNSIGNED NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_offer_number (offer_number),
                KEY idx_agreement_id (agreement_id),
                KEY idx_transaction_type (transaction_type),
                KEY idx_property_type (property_type),
                KEY idx_city (city),
                KEY idx_district (district),
                KEY idx_owner_user_id (owner_user_id),
                KEY idx_export_www (export_www)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['property_media']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                property_id BIGINT UNSIGNED NOT NULL,
                media_type VARCHAR(30) NOT NULL,
                attachment_id BIGINT UNSIGNED NULL,
                media_url VARCHAR(255) NULL,
                position SMALLINT UNSIGNED NOT NULL DEFAULT 0,
                is_primary TINYINT(1) NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                KEY idx_property_id (property_id),
                KEY idx_media_type (media_type)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['searches']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                agreement_id BIGINT UNSIGNED NULL,
                search_number VARCHAR(80) NOT NULL,
                transaction_type VARCHAR(20) NOT NULL,
                property_type VARCHAR(120) NULL,
                budget_from DECIMAL(14,2) NULL,
                budget_to DECIMAL(14,2) NULL,
                area_from DECIMAL(10,2) NULL,
                area_to DECIMAL(10,2) NULL,
                rooms_from SMALLINT UNSIGNED NULL,
                rooms_to SMALLINT UNSIGNED NULL,
                floor_from SMALLINT NULL,
                floor_to SMALLINT NULL,
                location_text VARCHAR(255) NULL,
                description LONGTEXT NULL,
                criteria_json LONGTEXT NULL,
                owner_user_id BIGINT UNSIGNED NULL,
                created_by BIGINT UNSIGNED NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_search_number (search_number),
                KEY idx_agreement_id (agreement_id),
                KEY idx_transaction_type (transaction_type),
                KEY idx_owner_user_id (owner_user_id)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['search_clients']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                search_id BIGINT UNSIGNED NOT NULL,
                client_id BIGINT UNSIGNED NOT NULL,
                created_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_search_client (search_id, client_id),
                KEY idx_client_id (client_id)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['agreement_stages']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                agreement_id BIGINT UNSIGNED NOT NULL,
                stage_name VARCHAR(120) NOT NULL,
                stage_date DATE NOT NULL,
                created_by BIGINT UNSIGNED NULL,
                created_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                KEY idx_agreement_id (agreement_id),
                KEY idx_stage_date (stage_date)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['transactions']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                agreement_id BIGINT UNSIGNED NOT NULL,
                property_id BIGINT UNSIGNED NULL,
                agreement_number VARCHAR(80) NOT NULL,
                property_label VARCHAR(255) NULL,
                transaction_type VARCHAR(20) NOT NULL,
                offer_price DECIMAL(14,2) NULL,
                price_currency VARCHAR(3) NOT NULL DEFAULT 'PLN',
                commission_amount DECIMAL(14,2) NULL,
                commission_unit VARCHAR(10) NULL,
                commission_stage_name VARCHAR(120) NULL,
                commission_stages_json LONGTEXT NULL,
                transaction_price DECIMAL(14,2) NOT NULL,
                transaction_date DATE NULL,
                cooperation_agent TINYINT(1) NOT NULL DEFAULT 0,
                cooperation_type VARCHAR(20) NULL,
                cooperation_agent_user_id BIGINT UNSIGNED NULL,
                cooperation_office_name VARCHAR(190) NULL,
                cooperation_agent_name VARCHAR(190) NULL,
                owner_user_id BIGINT UNSIGNED NULL,
                created_by BIGINT UNSIGNED NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                KEY idx_agreement_id (agreement_id),
                KEY idx_property_id (property_id),
                KEY idx_transaction_type (transaction_type),
                KEY idx_owner_user_id (owner_user_id),
                KEY idx_cooperation_agent_user_id (cooperation_agent_user_id),
                KEY idx_transaction_date (transaction_date)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['agent_profiles']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                user_id BIGINT UNSIGNED NOT NULL,
                phone VARCHAR(50) NULL,
                email VARCHAR(190) NULL,
                address_line VARCHAR(255) NULL,
                city VARCHAR(120) NULL,
                postal_code VARCHAR(20) NULL,
                bio LONGTEXT NULL,
                photo_id BIGINT UNSIGNED NULL,
                office_id BIGINT UNSIGNED NULL,
                is_public TINYINT(1) NOT NULL DEFAULT 1,
                display_order INT NOT NULL DEFAULT 100,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_user_id (user_id),
                KEY idx_office_id (office_id),
                KEY idx_display_order (display_order)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['offices']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                office_name VARCHAR(190) NOT NULL,
                office_email VARCHAR(190) NULL,
                office_phone VARCHAR(50) NULL,
                address_line VARCHAR(255) NULL,
                city VARCHAR(120) NULL,
                postal_code VARCHAR(20) NULL,
                description LONGTEXT NULL,
                logo_id BIGINT UNSIGNED NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                is_public TINYINT(1) NOT NULL DEFAULT 1,
                display_order INT NOT NULL DEFAULT 100,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                KEY idx_office_name (office_name),
                KEY idx_is_active (is_active),
                KEY idx_display_order (display_order)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['settings']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                setting_key VARCHAR(120) NOT NULL,
                setting_value LONGTEXT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY uq_setting_key (setting_key)
            ) {$charset_collate};",

            "CREATE TABLE {$tables['exports_queue']} (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                property_id BIGINT UNSIGNED NOT NULL,
                export_target VARCHAR(30) NOT NULL,
                payload_json LONGTEXT NULL,
                export_status VARCHAR(30) NOT NULL DEFAULT 'pending',
                attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
                last_error TEXT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                PRIMARY KEY (id),
                KEY idx_property_id (property_id),
                KEY idx_export_status (export_status),
                KEY idx_export_target (export_target)
            ) {$charset_collate};",
        ];
    }

    /**
     * @return array<string, string>
     */
    public static function tables(string $prefix): array
    {
        return [
            'clients' => "{$prefix}eocrm_clients",
            'client_addresses' => "{$prefix}eocrm_client_addresses",
            'agreements' => "{$prefix}eocrm_agreements",
            'agreement_clients' => "{$prefix}eocrm_agreement_clients",
            'properties' => "{$prefix}eocrm_properties",
            'property_media' => "{$prefix}eocrm_property_media",
            'searches' => "{$prefix}eocrm_searches",
            'search_clients' => "{$prefix}eocrm_search_clients",
            'agreement_stages' => "{$prefix}eocrm_agreement_stages",
            'transactions' => "{$prefix}eocrm_transactions",
            'agent_profiles' => "{$prefix}eocrm_agent_profiles",
            'offices' => "{$prefix}eocrm_offices",
            'settings' => "{$prefix}eocrm_settings",
            'exports_queue' => "{$prefix}eocrm_exports_queue",
        ];
    }
}
